import { z } from 'zod';
import { createTRPCRouter, protectedProcedure } from '@/server/trpc';
import { TRPCError } from '@trpc/server';
import Stripe from 'stripe';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-06-20',
  });

  export const paymentsRouter = createTRPCRouter({
    /**
       * Create a Stripe PaymentIntent for a listing purchase
          * Visby takes 2.5% fee, seller receives 97.5%
             */
               createPaymentIntent: protectedProcedure
                   .input(
                         z.object({
                                 listingId: z.string().uuid(),
                                         currency: z.string().default('usd'),
                                               })
                                                   )
                                                       .mutation(async ({ ctx, input }) => {
                                                             // Get listing details
                                                                   const { data: listing } = await ctx.supabase
                                                                           .from('listings')
                                                                                   .select('*, profiles:seller_id(stripe_account_id)')
                                                                                           .eq('id', input.listingId)
                                                                                                   .eq('status', 'active')
                                                                                                           .single();

                                                                                                                 if (!listing) throw new TRPCError({ code: 'NOT_FOUND', message: 'Listing not found or no longer active' });

                                                                                                                       const amountInCents = Math.round(listing.price_usd * 100);
                                                                                                                             const visbyFee = Math.round(amountInCents * 0.025); // 2.5% fee

                                                                                                                                   const paymentIntent = await stripe.paymentIntents.create({
                                                                                                                                           amount: amountInCents,
                                                                                                                                                   currency: input.currency.toLowerCase(),
                                                                                                                                                           metadata: {
                                                                                                                                                                     listing_id: input.listingId,
                                                                                                                                                                               buyer_id: ctx.session.user.id,
                                                                                                                                                                                         seller_id: listing.seller_id,
                                                                                                                                                                                                   visby_fee: visbyFee.toString(),
                                                                                                                                                                                                           },
                                                                                                                                                                                                                   automatic_payment_methods: { enabled: true },
                                                                                                                                                                                                                         });

                                                                                                                                                                                                                               // Store pending order in Supabase
                                                                                                                                                                                                                                     await ctx.supabase.from('orders').insert({
                                                                                                                                                                                                                                             listing_id: input.listingId,
                                                                                                                                                                                                                                                     buyer_id: ctx.session.user.id,
                                                                                                                                                                                                                                                             seller_id: listing.seller_id,
                                                                                                                                                                                                                                                                     amount_usd: listing.price_usd,
                                                                                                                                                                                                                                                                             visby_fee_usd: visbyFee / 100,
                                                                                                                                                                                                                                                                                     stripe_payment_intent_id: paymentIntent.id,
                                                                                                                                                                                                                                                                                             status: 'pending',
                                                                                                                                                                                                                                                                                                   });

                                                                                                                                                                                                                                                                                                         return {
                                                                                                                                                                                                                                                                                                                 clientSecret: paymentIntent.client_secret!,
                                                                                                                                                                                                                                                                                                                         amount: amountInCents,
                                                                                                                                                                                                                                                                                                                                 currency: input.currency,
                                                                                                                                                                                                                                                                                                                                       };
                                                                                                                                                                                                                                                                                                                                           }),

                                                                                                                                                                                                                                                                                                                                             /**
                                                                                                                                                                                                                                                                                                                                                * Get order history for current user
                                                                                                                                                                                                                                                                                                                                                   */
                                                                                                                                                                                                                                                                                                                                                     getMyOrders: protectedProcedure.query(async ({ ctx }) => {
                                                                                                                                                                                                                                                                                                                                                         const { data, error } = await ctx.supabase
                                                                                                                                                                                                                                                                                                                                                               .from('orders')
                                                                                                                                                                                                                                                                                                                                                                     .select(`'use client';

                                                                                                                                                                                                                                                                                                                                                                        import { useState } from 'react';
                                                                                                                                                                                                                                                                                                                                                                        import { usePrivy } from '@privy-io/react-auth';
                                                                                                                                                                                                                                                                                                                                                                        import { Button } from '@/components/ui/button';
                                                                                                                                                                                                                                                                                                                                                                        import { ShoppingCart, Loader2 } from 'lucide-react';

                                                                                                                                                                                                                                                                                                                                                                        interface Item {
                                                                                                                                                                                                                                                                                                                                                                          id: string;
                                                                                                                                                                                                                                                                                                                                                                            name: string;
                                                                                                                                                                                                                                                                                                                                                                              serial_number: string;
                                                                                                                                                                                                                                                                                                                                                                                price: number;
                                                                                                                                                                                                                                                                                                                                                                                  currency: string;
                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                  export function BuyButton({ item }: { item: Item }) {
                                                                                                                                                                                                                                                                                                                                                                                    const { ready, authenticated, login, user } = usePrivy();
                                                                                                                                                                                                                                                                                                                                                                                      const [loading, setLoading] = useState(false);

                                                                                                                                                                                                                                                                                                                                                                                        async function handleBuy() {
                                                                                                                                                                                                                                                                                                                                                                                            if (!authenticated) {
                                                                                                                                                                                                                                                                                                                                                                                                  login();
                                                                                                                                                                                                                                                                                                                                                                                                        return;
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                setLoading(true);
                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                          const res = await fetch('/api/checkout', {
                                                                                                                                                                                                                                                                                                                                                                                                                                  method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                          headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                  body: JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                            itemId: item.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      itemName: item.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                serialNumber: item.serial_number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          priceUsd: item.price,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    buyerEmail: user?.email?.address,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              successUrl: `${window.location.origin}/purchase/success`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cancelUrl: window.location.href,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const { url } = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (url) window.location.href = url;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Checkout failed:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                size="lg"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 text-white shadow-lg shadow-purple-500/25"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onClick={handleBuy}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={!ready || loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Loader2 className="mr-2 h-4 w-4 animate-# ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # VISBY — Environment Variables
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Copy this file to .env.local and fill in your values
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ============================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # --- Privy (Auth + Embedded Wallets) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Get from: https://dashboard.privy.io
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NEXT_PUBLIC_PRIVY_APP_ID=your_privy_app_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                PRIVY_APP_SECRET=your_privy_app_secret
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # --- Supabase (Database) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Get from: https://supabase.com/dashboard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SUPABASE_SERVICE_ROLE_KEY=your_supabase_service_role_key
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # --- Helius (Solana RPC) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Get from: https://helius.dev (free: 100k req/day)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NEXT_PUBLIC_HELIUS_RPC_URL=https://mainnet.helius-rpc.com/?api-key=your_key
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                HELIUS_API_KEY=your_helius_api_key
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # --- Stripe (Fiat Payments) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Get from: https://dashboard.stripe.com/apikeys
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_your_key
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                STRIPE_SECRET_KEY=sk_test_your_key
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                STRIPE_WEBHOOK_SECRET=whsec_your_webhook_secret
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # --- Solana Wallet (Server-Side Minting) ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Base58-encoded private key for the Visby minting wallet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # NEVER commit this value — use a dedicated minting wallet with minimal SOL
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                SOLANA_MINTING_KEYPAIR=your_base58_keypair
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # --- App ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NEXT_PUBLIC_APP_URL=http://localhost:3000
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NEXT_PUBLIC_SOLANA_NETWORK=mainnet-betaspin" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <ShoppingCart className="mr-2 h-4 w-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {authenticated ? 'Buy Now' : 'Connect to Buy'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-xs text-center text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Pay with card or crypto &bull; NFT ownership transfers instantly
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                             *,
                                                                                                                                                                                                                                                                                                                                                                                     listings:listing_id(title, images, category),
                                                                                                                                                                                                                                                                                                                                                                                             seller:seller_id(username, avatar_url)
                                                                                                                                                                                                                                                                                                                                                                                                   `)
                                                                                                                                                                                                                                                                                                                                                                                                         .eq('buyer_id', ctx.session.user.id)
                                                                                                                                                                                                                                                                                                                                                                                                               .order('created_at', { ascending: false });

                                                                                                                                                                                                                                                                                                                                                                                                                   if (error) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR' });
                                                                                                                                                                                                                                                                                                                                                                                                                       return data ?? [];
                                                                                                                                                                                                                                                                                                                                                                                                                         }),
                                                                                                                                                                                                                                                                                                                                                                                                                         });