import Link from 'next/link';

export function Footer() {
  return (
      <footer className="border-t border-border/40 bg-background">
            <div className="container py-12 grid grid-cols-2 md:grid-cols-4 gap-8">
                    <div className="col-span-2 md:col-span-1">
                              <div className="flex items-center gap-2 font-bold text-lg mb-3">
                                          <div className="w-7 h-7 rounded-lg bg-gradient-to-br from-purple-600 to-amber-400 flex items-center justify-center text-white text-xs font-black">
                                                        V
                                                                    </div>
                                                                                <span className="bg-gradient-to-r from-purple-600 to-amber-500 bg-clip-text text-transparent">
                                                                                              Visby
                                                                                                          </span>
                                                                                                                    </div>
                                                                                                                              <p className="text-xs text-muted-foreground max-w-[200px]">
                                                                                                                                          Fraud-free NFT provenance for real-world goods. Built on Solana.
                                                                                                                                                    </p>
                                                                                                                                                            </div>

                                                                                                                                                                    <div>
                                                                                                                                                                              <h4 className="text-sm font-semibold mb-3">Marketplace</h4>
                                                                                                                                                                                        <ul className="space-y-2 text-sm text-muted-foreground">
                                                                                                                                                                                                    <li><Link href="/marketplace" className="hover:text-foreground transition-colors">Browse All</Link></li>
                                                                                                                                                                                                                <li><Link href="/marketplace?category=sneakers" className="hover:text-foreground transition-colors">Sneakers</Link></li>
                                                                                                                                                                                                                            <li><Link href="/marketplace?category=watches" className="hover:text-foreground transition-colors">Watches</Link></li>
                                                                                                                                                                                                                                        <li><Link href="/marketplace?category=electronics" className="hover:text-foreground transition-colors">Electronics</Link></li>
                                                                                                                                                                                                                                                  </ul>
                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                            <h4 className="text-sm font-semibold mb-3">Developers</h4>
                                                                                                                                                                                                                                                                                      <ul className="space-y-2 text-sm text-muted-foreground">
                                                                                                                                                                                                                                                                                                  <li><Link href="/sdk" className="hover:text-foreground transition-colors">Pay with Visby SDK</Link></li>
                                                                                                                                                                                                                                                                                                              <li><Link href="/docs" className="hover:text-foreground transition-colors">Documentation</Link></li>
                                                                                                                                                                                                                                                                                                                          <li><Link href="/docs/api" className="hover:text-foreground transition-colors">API Reference</Link></li>
                                                                                                                                                                                                                                                                                                                                      <li><Link href="/docs/webhooks" className="hover:text-foreground transition-colors">Webhooks</Link></li>
                                                                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                          <h4 className="text-sm font-semibold mb-3">Company</h4>
                                                                                                                                                                                                                                                                                                                                                                                    <ul className="space-y-2 text-sm text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                <li><Link href="/about" className="hover:text-foreground transition-colors">About</Link></li>
                                                                                                                                                                                                                                                                                                                                                                                                            <li><Link href="/blog" className="hover:text-foreground transition-colors">Blog</Link></li>
                                                                                                                                                                                                                                                                                                                                                                                                                        <li><Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <li><Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link></li>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="container border-t border-border/40 py-4 flex flex-col md:flex-row items-center justify-between gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-xs text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    &copy; {new Date().getFullYear()} Visby. All rights reserved.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-xs text-muted-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Built on{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="https://solana.com" target="_blank" rel="noreferrer" className="underline hover:text-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Solana
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {' '}&bull;{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Powered by Metaplex &bull; ~$0.00025/mint
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }