src/lib/supabase/client.ts
/**
 *  * Visby NFT Provenance Minting
  * Uses Metaplex Core on Solana for ultra-cheap (~$0.00025) NFT minting
   */
   import { createUmi } from '@metaplex-foundation/umi-bundle-defaults';
   import {
     createV1,
       mplCore,
       } from '@metaplex-foundation/mpl-core';
       import {
         generateSigner,
           signerIdentity,
             createSignerFromKeypair,
               keypairIdentity,
               } from '@metaplex-foundation/umi';
               import { Connection, PublicKey } from '@solana/web3.js';

               export interface ProvenanceAttribute {
                 trait_type: string;
                   value: string;
                   }

                   export interface ProvenanceEvent {
                     owner: string;
                       wallet: string;
                         profile: string;
                           timestamp: string;
                             tx: string;
                               event: 'mint' | 'transfer' | 'sale';
                                 price?: number;
                                   currency?: string;
                                   }

                                   export interface ProvenanceMetadata {
                                     name: string;
                                       description: string;
                                         image: string;
                                           attributes: ProvenanceAttribute[];
                                             provenance: ProvenanceEvent[];
                                               serial_number: string;
                                                 visby_version: string;
                                                 }

                                                 export interface MintProvenanceNFTParams {
                                                   name: string;
                                                     serialNumber: string;
                                                       brand: string;
                                                         category: string;
                                                           condition: string;
                                                             manufactureDate: string;
                                                               imageUri: string;
                                                                 ownerName: string;
                                                                   ownerWallet: string;
                                                                     ownerProfile: string;
                                                                       metadataUri: string; // Pre-uploaded to Arweave/NFT.Storage
                                                                       }

                                                                       /**
                                                                        * Builds the provenance metadata object for a new item mint
                                                                         */
                                                                         export function buildProvenanceMetadata(
                                                                           params: MintProvenanceNFTParams,
                                                                             txHash: string = 'pending'
                                                                             ): ProvenanceMetadata {
                                                                               return {
                                                                                   name: `${params.name} — SN: ${params.serialNumber}`,
                                                                                       description: 'Authenticated provenance record issued by Visby',
                                                                                           image: params.imageUri,
                                                                                               attributes: [
                                                                                                     { trait_type: 'Serial Number', value: params.serialNumber },
                                                                                                           { trait_type: 'Product Category', value: params.category },
                                                                                                                 { trait_type: 'Brand', value: params.brand },
                                                                                                                       { trait_type: 'Manufacture Date', value: params.manufactureDate },
                                                                                                                             { trait_type: 'Condition', value: params.condition },
                                                                                                                                   { trait_type: 'Platform', value: 'Visby' },
                                                                                                                                         { trait_type: 'Chain', value: 'Solana' },
                                                                                                                                             ],
                                                                                                                                                 provenance: [
                                                                                                                                                       {
                                                                                                                                                               owner: params.ownerName,
                                                                                                                                                                       wallet: params.ownerWallet,
                                                                                                                                                                               profile: params.ownerProfile,
                                                                                                                                                                                       timestamp: new Date().toISOString(),
                                                                                                                                                                                               tx: txHash,
                                                                                                                                                                                                       event: 'mint',
                                                                                                                                                                                                             },
                                                                                                                                                                                                                 ],
                                                                                                                                                                                                                     serial_number: params.serialNumber,
                                                                                                                                                                                                                         visby_version: '1.0.0',
                                                                                                                                                                                                                           };
                                                                                                                                                                                                                           }

                                                                                                                                                                                                                           /**
                                                                                                                                                                                                                            * Mint a provenance NFT using Metaplex Core
                                                                                                                                                                                                                             * @returns The NFT mint address
                                                                                                                                                                                                                              */
                                                                                                                                                                                                                              export async function mintProvenanceNFT(
                                                                                                                                                                                                                                rpcUrl: string,
                                                                                                                                                                                                                                  payerPrivateKey: Uint8Array,
                                                                                                                                                                                                                                    params: MintProvenanceNFTParams
                                                                                                                                                                                                                                    ): Promise<{ mintAddress: string; txHash: string }> {
                                                                                                                                                                                                                                      const umi = createUmi(rpcUrl).use(mplCore());

                                                                                                                                                                                                                                        // Set up payer
                                                                                                                                                                                                                                          const payerKeypair = umi.eddsa.createKeypairFromSecretKey(payerPrivateKey);
                                                                                                                                                                                                                                            umi.use(keypairIdentity(payerKeypair));

                                                                                                                                                                                                                                              // Generate new asset signer
                                                                                                                                                                                                                                                const asset = generateSigner(umi);

                                                                                                                                                                                                                                                  // Mint the NFT
                                                                                                                                                                                                                                                    const tx = await createV1(umi, {
                                                                                                                                                                                                                                                        asset,
                                                                                                                                                                                                                                                            name: `${params.name} — SN: ${params.serialNumber}`,
                                                                                                                                                                                                                                                                uri: params.metadataUri,
                                                                                                                                                                                                                                                                  }).sendAndConfirm(umi);

                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                        mintAddress: asset.publicKey.toString(),
                                                                                                                                                                                                                                                                            txHash: Buffer.from(tx.signature).toString('base64'),
                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                              /**
                                                                                                                                                                                                                                                                               * Verify a serial number is registered on-chain
                                                                                                                                                                                                                                                                                */
                                                                                                                                                                                                                                                                                export async function verifySerialNumber(
                                                                                                                                                                                                                                                                                  rpcUrl: string,
                                                                                                                                                                                                                                                                       import { createUmi } from '@metaplex-foundation/umi-bundle-defaults';
                                                                                                                                                                                                                                                                       import { mplCore, create, fetchAsset } from '@metaplex-foundation/mpl-core';
                                                                                                                                                                                                                                                                       import { generateSigner, signerIdentity, publicKey } from '@metaplex-foundation/umi';
                                                                                                                                                                                                                                                                       import { irysUploader } from '@metaplex-foundation/umi-uploader-irys';
                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                       export interface ProvenanceMetadata {
                                                                                                                                                                                                                                                                         name: string;
                                                                                                                                                                                                                                                                           serialNumber: string;
                                                                                                                                                                                                                                                                             category: string;
                                                                                                                                                                                                                                                                               brand: string;
                                                                                                                                                                                                                                                                                 manufactureDate: string;
                                                                                                                                                                                                                                                                                   condition: string;
                                                                                                                                                                                                                                                                                     description?: string;
                                                                                                                                                                                                                                                                                       imageUri?: string;
                                                                                                                                                                                                                                                                                         ownerWallet: string;
                                                                                                                                                                                                                                                                                           ownerProfile: string;
                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                           export interface ProvenanceEvent {
                                                                                                                                                                                                                                                                                             owner: string;
                                                                                                                                                                                                                                                                                               wallet: string;
                                                                                                                                                                                                                                                                                                 profile: string;
                                                                                                                                                                                                                                                                                                   timestamp: string;
                                                                                                                                                                                                                                                                                                     tx: string;
                                                                                                                                                                                                                                                                                                       event: 'mint' | 'transfer' | 'list' | 'sale';
                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                       export async function mintProvenanceNFT(
                                                                                                                                                                                                                                                                                                         metadata: ProvenanceMetadata,
                                                                                                                                                                                                                                                                                                           payerKeypair: Uint8Array
                                                                                                                                                                                                                                                                                                           ) {
                                                                                                                                                                                                                                                                                                             const rpcUrl = process.env.NEXT_PUBLIC_HELIUS_RPC_URL!;
                                                                                                                                                                                                                                                                                                               const umi = createUmi(rpcUrl)
                                                                                                                                                                                                                                                                                                                   .use(mplCore())
                                                                                                                                                                                                                                                                                                                       .use(irysUploader());
                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                         // Build full metadata JSON
                                                                                                                                                                                                                                                                                                                           const metadataJson = {
                                                                                                                                                                                                                                                                                                                               name: `${metadata.brand} ${metadata.name} — SN: ${metadata.serialNumber}`,
                                                                                                                                                                                                                                                                                                                                   description: metadata.description ?? 'Authenticated provenance record by Visby',
                                                                                                                                                                                                                                                                                                                                       image: metadata.imageUri ?? '',
                                                                                                                                                                                                                                                                                                                                           attributes: [
                                                                                                                                                                                                                                                                                                                                                 { trait_type: 'Serial Number', value: metadata.serialNumber },
                                                                                                                                                                                                                                                                                                                                                       { trait_type: 'Product Category', value: metadata.category },
                                                                                                                                                                                                                                                                                                                                                             { trait_type: 'Brand', value: metadata.brand },
                                                                                                                                                                                                                                                                                                                                                                   { trait_type: 'Manufacture Date', value: metadata.manufactureDate },
                                                                                                                                                                                                                                                                                                                                                                         { trait_type: 'Condition', value: metadata.condition },
                                                                                                                                                                                                                                                                                                                                                                             ],
                                                                                                                                                                                                                                                                                                                                                                                 provenance: [
                                                                                                                                                                                                                                                                                                                                                                                       {
                                                                                                                                                                                                                                                                                                                                                                                               owner: metadata.brand,
                                                                                                                                                                                                                                                                                                                                                                                                       wallet: metadata.ownerWallet,
                                                                                                                                                                                                                                                                                                                                                                                                               profile: metadata.ownerProfile,
                                                                                                                                                                                                                                                                                                                                                                                                                       timestamp: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                               tx: 'pending',
                                                                                                                                                                                                                                                                                                                                                                                                                                       event: 'mint',
                                                                                                                                                                                                                                                                                                                                                                                                                                             } as ProvenanceEvent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                 ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                   };
                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Upload metadata to Arweave via Irys
                                                                                                                                                                                                                                                                                                                                                                                                                                                       const [metadataUri] = await umi.uploader.uploadJson([metadataJson]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Create the NFT asset using Metaplex Core
                                                                                                                                                                                                                                                                                                                                                                                                                                                           const assetSigner = generateSigner(umi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                             const { signature } = await create(umi, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 asset: assetSigner,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     name: metadataJson.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         uri: metadataUri,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }).sendAndConfirm(umi);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 mintAddress: assetSigner.publicKey.toString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     metadataUri,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         signature: Buffer.from(signature).toString('base64'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             serialNumber: metadata.serialNumber,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               export async function transferProvenanceNFT(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 mintAddress: string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   fromWallet: string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     toWallet: string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       salePrice: number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         currency: string
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // This is called after payment is confirmed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Transfers the Core NFT asset to the buyer's wallet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const rpcUrl = process.env.NEXT_PUBLIC_HELIUS_RPC_URL!;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const umi = createUmi(rpcUrl).use(mplCore());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Transfer logic would be implemented here with the actual
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // seller's signer once Privy embedded wallet signs the transaction
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               fromWallet,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   toWallet,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       mintAddress,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           timestamp: new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }             serialNumber: string,
                                                                                                                                                                                                                                                                                      registryProgramId: string
                                                                                                                                                                                                                                                                                      ): Promise<boolean> {
                                                                                                                                                                                                                                                                                        const connection = new Connection(rpcUrl, 'confirmed');
                                                                                                                                                                                                                                                                                          // In production, this queries the on-chain registry program
                                                                                                                                                                                                                                                                                            // For now, returns true for demo purposes
                                                                                                                                                                                                                                                                                              console.log(`Verifying serial: ${serialNumber} against registry: ${registryProgramId}`);
                                                                                                                                                                                                                                                                                                return true;
                                                                                                                                                                                                                                                                                                }
 */