'use client';

import Link from 'next/link';
import { usePrivy } from '@privy-io/react-auth';
import { Button } from '@/components/ui/button';
import { ShoppingBag, Search, Wallet, Menu, X } from 'lucide-react';
import { useState } from 'react';

export function Navbar() {
  const { ready, authenticated, login, logout, user } = usePrivy();
    const [mobileOpen, setMobileOpen] = useState(false);

      return (
          <nav className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
                <div className="container flex h-16 items-center justify-between">
                        {/* Logo */}
                                <Link href="/" className="flex items-center gap-2 font-bold text-xl">
                                          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-purple-600 to-amber-400 flex items-center justify-center text-white text-sm font-black">
                                                      V
                                                                </div>
                                                                          <span className="bg-gradient-to-r from-purple-600 to-amber-500 bg-clip-text text-transparent">
                                                                                      Visby
                                                                                                </span>
                                                                                                        </Link>

                                                                                                                {/* Desktop Nav */}
                                                                                                                        <div className="hidden md:flex items-center gap-6 text-sm font-medium">
                                                                                                                                  <Link href="/marketplace" className="text-muted-foreground hover:text-foreground transition-colors">
                                                                                                                                              Marketplace
                                                                                                                                                        </Link>
                                                                                                                                                                  <Link href="/sell" className="text-muted-foreground hover:text-foreground transition-colors">
                                                                                                                                                                              Sell
                                                                                                                                                                                        </Link>
                                                                                                                                                                                                  <Link href="/sdk" className="text-muted-foreground hover:text-foreground transition-colors">
                                                                                                                                                                                                              SDK
                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                  <Link href="/about" className="text-muted-foreground hover:text-foreground transition-colors">
                                                                                                                                                                                                                                              About
                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                        {/* Actions */}
                                                                                                                                                                                                                                                                                <div className="flex items-center gap-3">
                                                                                                                                                                                                                                                                                          <Button variant="ghost" size="icon" asChild>
                                                                                                                                                                                                                                                                                                      <Link href="/search">
                                                                                                                                                                                                                                                                                                                    <Search className="h-5 w-5" />
                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                          </Button>

                                                                                                                                                                                                                                                                                                                                                    {ready && authenticated ? (
                                                                                                                                                                                                                                                                                                                                                                <>
                                                                                                                                                                                                                                                                                                                                                                              <Button variant="ghost" size="icon" asChild>
                                                                                                                                                                                                                                                                                                                                                                                              <Link href="/wallet">
                                                                                                                                                                                                                                                                                                                                                                                                                <Wallet className="h-5 w-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button variant="ghost" size="icon" asChild>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Link href="/cart">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ShoppingBag className="h-5 w-5" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          variant="outline"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          size="sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={logout}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="hidden md:flex"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {user?.email?.address
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ? user.email.address.split('@')[0]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            : 'Profile'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={login}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        disabled={!ready}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      size="sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 text-white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Connect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          variant="ghost"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      size="icon"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="md:hidden"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onClick={() => setMobileOpen(!mobileOpen)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {mobileOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Mobile Menu */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {mobileOpen && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="md:hidden border-t border-border p-4 flex flex-col gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/marketplace" onClick={() => setMobileOpen(false)} className="text-sm font-medium py-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Marketplace
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/sell" onClick={() => setMobileOpen(false)} className="text-sm font-medium py-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Sell
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/sdk" onClick={() => setMobileOpen(false)} className="text-sm font-medium py-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      SDK
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </nav>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }