'use client';

import Link from 'next/link';
import { usePrivy } from '@privy-io/react-auth';
import { Button } from '@/components/ui/button';
import { ArrowRight, Shield, Zap, Globe } from 'lucide-react';

export function HeroSection() {
  const { ready, authenticated, login } = usePrivy();

    return (
        <section className="relative overflow-hidden bg-gradient-to-b from-background to-muted/30 pt-20 pb-32">
              {/* Background gradient orbs */}
                    <div className="absolute inset-0 overflow-hidden pointer-events-none">
                            <div className="absolute -top-40 -right-40 w-80 h-80 rounded-full bg-purple-600/20 blur-3xl" />
                                    <div className="absolute -bottom-40 -left-40 w-80 h-80 rounded-full bg-amber-400/20 blur-3xl" />
                                          </div>

                                                <div className="container relative">
                                                        <div className="max-w-3xl mx-auto text-center">
                                                                  {/* Badge */}
                                                                            <div className="inline-flex items-center gap-2 rounded-full border border-purple-200 dark:border-purple-800 bg-purple-50 dark:bg-purple-950/50 px-4 py-1.5 text-sm text-purple-700 dark:text-purple-300 mb-6">
                                                                                        <Zap className="w-3.5 h-3.5" />
                                                                                                    Built on Solana &bull; ~$0.00025 per NFT mint
                                                                                                              </div>

                                                                                                                        {/* Headline */}
                                                                                                                                  <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight mb-6">
                                                                                                                                              Every product has a{' '}
                                                                                                                                                          <span className="bg-gradient-to-r from-purple-600 via-purple-500 to-amber-500 bg-clip-text text-transparent">
                                                                                                                                                                        story on-chain
                                                                                                                                                                                    </span>
                                                                                                                                                                                              </h1>

                                                                                                                                                                                                        <p className="text-lg md:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
                                                                                                                                                                                                                    Visby mints an NFT provenance record for every physical item &mdash; sneakers, watches, electronics &mdash; so you always know what you&apos;re buying is genuine.
                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                        {/* CTAs */}
                                                                                                                                                                                                                                                  <div className="flex flex-col sm:flex-row gap-3 justify-center mb-12">
                                                                                                                                                                                                                                                              <Button asChild size="lg" className="bg-gradient-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800 text-white shadow-lg shadow-purple-500/25">
                                                                                                                                                                                                                                                                            <Link href="/marketplace">
                                                                                                                                                                                                                                                                                            Browse Marketplace <ArrowRight className="ml-2 h-4 w-4" />
                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                  {!authenticated && ready && (
                                                                                                                                                                                                                                                                                                                                                <Button size="lg" variant="outline" onClick={login}>
                                                                                                                                                                                                                                                                                                                                                                Start Selling Free
                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                      {authenticated && (
                                                                                                                                                                                                                                                                                                                                                                                                                    <Button asChild size="lg" variant="outline">
                                                                                                                                                                                                                                                                                                                                                                                                                                    <Link href="/sell">List an Item</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* Stats */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="grid grid-cols-3 gap-6 max-w-lg mx-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-2xl font-bold text-purple-600">$0.00025</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-xs text-muted-foreground mt-1">Per NFT mint</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="text-center border-x border-border">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-2xl font-bold text-purple-600">2.5%</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-xs text-muted-foreground mt-1">Platform fee</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-2xl font-bold text-purple-600">135+</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="text-xs text-muted-foreground mt-1">Currencies</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }